
services:
  # 1. MINIO : Notre stockage S3 local
  minio:
    image: bitnamilegacy/minio:2025.7.23-debian-12-r5
    container_name: minio
    command: minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"   # API S3 utilisée par Spark
      - "9090:9001"   # Console web (accès via localhost:9090)
    volumes:
      - ../data/minio:/data
    networks:
      - lakehouse-net

  # 3. SPARK MASTER : Coordinateur enrichi avec Delta et Iceberg (via le Dockerfile)
  spark-master-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master-lab
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8080" # UI Spark Master
      - "7078:7077" # Port de soumission PySpark
    volumes:
      - ../spark_jobs:/opt/bitnami/spark/jobs
      - ../data:/opt/bitnami/spark/data
    networks:
      - lakehouse-net

  # 4. SPARK WORKER : Exécuteur (Ressources limitées pour ne pas crasher ta machine)
  spark-worker-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-lab
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-lab:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    ports:
      - "8083:8081" # UI Spark Worker
    depends_on:
      - spark-master-lab
    volumes:
      - ../spark_jobs:/opt/bitnami/spark/jobs
      - ../data:/opt/bitnami/spark/data
    networks:
      - lakehouse-net

  # 5. STREAMLIT APP : Dashboard d'analyse de performances
  streamlit-app:
    build:
      context: ..
      dockerfile: Dockerfile.app
    container_name: streamlit-app
    ports:
      - "8502:8501"
    volumes:
      - ../data:/app/data
      - ../app.py:/app/app.py
    networks:
      - lakehouse-net

networks:
  lakehouse-net:
    driver: bridge